### ISSUE TITLE
Automate plugin revision update

### ISSUE THREAD

**Issue by m15a** [m15a/nixpkgs-vim-plugins#1]
## TODO

- [x] Create script to update plugins. f9d6bd8d878f8c981b8325f151cbfcfaa485d455
- [ ] #4
- [x] Auto generate plugin lists in README. ec03fc366cfa743171f4bf1412f51248e3d19212
- [x] Use GitHub [Nix Action][1].

[1]: https://github.com/marketplace/actions/install-nix
