### ISSUE TITLE
Enable to add plugin without updating all plugins

### ISSUE THREAD

**Issue by m15a** [m15a/nixpkgs-vim-plugins#11]
## TODO

- [x] Create lock file that records all info obtained from previous update: `.previous-update.json`
- [x] Add subcommand `update-vim-plugins update [spec ...]`
    - `update --all` updates all and `update` only add new entries.
- [x] ~~Update doc~~ no need.
