### ISSUE TITLE
Add checks

### ISSUE THREAD

**Issue by m15a** [m15a/nixpkgs-vim-plugins#14]
## TODO

- [x] Check missing licenses 0ad3e960672d68223a21689b69ef6c459e5651a5
- [x] ~~Check missing descriptions~~ missing description is filled by `No description` so it's ok.
- [x] Check broken packages: `nix flake check` does it.
