### ISSUE TITLE
Fill missing licenses

### ISSUE THREAD

**Issue by m15a** [m15a/nixpkgs-vim-plugins#16]
## TODO

- [x] ~~trace: warning: vimplugin-JpFormat-vim-2019-07-12 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-OneTerm-nvim-2021-07-30 has no license~~ **unknown**
- [x] trace: warning: vimplugin-ariake-vim-colors-2021-02-23 has no license: **MIT**
- [x] ~~trace: warning: vimplugin-blue-moon-2021-12-05 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-chadtree-2021-12-18 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-codeql-nvim-2021-12-08 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-consolation-nvim-2021-09-01 has no license~~ **unknown**
- [x] trace: warning: vimplugin-cutlass-nvim-2021-12-13 has no license: **WTFPL**
- [x] ~~trace: warning: vimplugin-dependency-assist-nvim-2021-11-11 has no license~~ **unknown** and the repo archived.
- [x] trace: warning: vimplugin-format-nvim-2021-12-12 has no license: **MIT**
- [x] trace: warning: vimplugin-goimpl-nvim-2021-12-07 has no license: **MIT**
- [x] ~~trace: warning: vimplugin-gruvy-2021-12-01 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-jazz-nvim-2019-04-30 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-lspactions-2021-11-15 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-lua-dev-nvim-2021-12-10 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-neovim-2021-12-17 has no license~~ **unknown**
    - NOTE: this is rose-pine/neovim, should be renamed to rose-pine or rose-pine-nvim.
- [x] trace: warning: vimplugin-nvim-base16-lua-2019-10-16 has no license: **MIT**
- [x] ~~trace: warning: vimplugin-nvim-cursorword-2021-12-16 has no license~~ **unknown**
- [x] trace: warning: vimplugin-nvim-deus-2021-08-26 has no license: **GPL3+**
- [x] ~~trace: warning: vimplugin-nvim-hybrid-2021-07-31 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-nvim-lspinstall-2021-07-23 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-nvim-lua-guide-2021-11-11 has no license~~
    - NOTE: this is not a plugin.
- [x] trace: warning: vimplugin-nvim-luapad-2021-08-15 has no license: **GPL3**
- [x] ~~trace: warning: vimplugin-nvim-rdark-2020-12-25 has no license~~ **unknown**
- [x] trace: warning: vimplugin-nvim-revJ-lua-2021-09-12 has no license: **Vim**
- [x] ~~trace: warning: vimplugin-nvim-transparent-2021-11-28 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-omni-vim-2021-02-20 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-plugin-template-nvim-2021-04-24 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-reaper-nvim-2021-01-29 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-roshnivim-cs-2021-12-17 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-substrata-nvim-2021-12-07 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-surround-nvim-2021-12-16 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-tidy-nvim-2021-11-22 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-toggleterm-nvim-2021-11-24 has no license~~ **unknown**
- [x] ~~trace: warning: vimplugin-vim-be-good-2021-03-16 has no license~~: **unknown**
    - NOTE: It contains tjdevries/vlog.nvim, which is distributed under the MIT license.
