### ISSUE TITLE
Overrides to fix build and add missing license

### ISSUE THREAD

**Issue by m15a** [m15a/nixpkgs-vim-plugins#8]
## TODO
- [x] Add overrides 1937895db95db3bd8b481ece93d508b88979b57f
- [x] Add missing licenses ad12b784da0fa4e4d87bac740264e8c3fbcdb37b
- [x] Add dependencies (for example, telescope extensions) 31b08e389037cdfd988e7eea5e1696c227a83b2b
